# Generated by Django 5.2.1 on 2025-05-08 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processo',
            name='setor_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origem', to='usuarios.setor'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='enviado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tramite',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.processo'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='setor_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites_destino', to='usuarios.setor'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='setor_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites_origem', to='usuarios.setor'),
        ),
    ]
